global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'airflow-stats'

    scrape_interval: 5s
    metrics_path: /admin/metrics

    static_configs:
        - targets: ['localhost:8080']
